### PR TITLE
added fake-data

### PR DESCRIPTION
**Pull request by Sukriti-sood**
This pull request is relate to issue #5

### CODE REVIEW

**Comment by adityabisoi** [comment]
@Sukriti-sood You need to add fake data with real-world names and email addresses (which must look real, but must be fake)
Example: first_name: John, second_name: Doe, email: johndoe@email.com

Please generate the data into a JSON file, so that it can be imported at production level.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood You need to add fake data with real-world names and email addresses (which must look real, but must be fake)
> Example: first_name: John, second_name: Doe, email: [johndoe@email.com](mailto:johndoe@email.com)
> 
> Please generate the data into a JSON file, so that it can be imported at production level.

Ook I will do these changes

**Comment by Sukriti-sood** [comment]
@adityabisoi I have made changes , Please have a look

**Comment by adityabisoi** [comment]
Please remove all other changes, except the fakedata file. The data should be in the following format:
```
{
"page": 1,
"data": [{
"first_name":"John",
"last_name":"Doe",
"email:"johndoe@gmail.com"
}]
}
```

**Comment by adityabisoi** [comment]
@Sukriti-sood This issue has been laying around for a long. Please remove all unnecessary changes, and include only the demo data file in the PR.

**Comment by Sukriti-sood** [comment]
> @Sukriti-sood This issue has been laying around for a long. Please remove all unnecessary changes, and include only the demo data file in the PR.

I have this confusion , do I need to remove import of json file from ser.ts and also adding of fakedata when user database is empty.

**Comment by adityabisoi** [comment]
Yes remove every import and just provide the demo data in the file.

**Pull request merged**
