### PR TITLE
Updated homepage with new routes

### LINKED ISSUE #90: Update home page endpoints info
**Describe the feature**
Update endpoints information on the home page.

**Tasks todo**
- [ ] Add `/foodphoto` with their additional params and query.
- [ ]  Add `/animals` with their additional params and query.
- [ ]  Add `/vehicles` with their additional params and query. 

**Are you working on this feature? (Yes/No)**
Yes

### PR DESCRIPTION
**Pull request by Samridhi-98**
# Related Issue

-   closes #90 

# Proposed Changes

- [x] Added /foodphoto with their additional params and query.
- [x] Added /animals with their additional params and query.
- [x] Added /vehicles with their additional params and query.

# Checklist

-   [x] Tests
-   [x] Translations

### CODE REVIEW

**Comment by Samridhi-98** [comment]
@ShauryaAg  @paramsiddharth  Please review my PR.

**Comment by ShauryaAg** [comment]
@Samridhi-98 #92 Adds an endpoint that fetches photos using their `id`. Can you add that too?

**Review by ShauryaAg — CHANGES_REQUESTED** [review]
@Samridhi-98 #92 Adds an endpoint that fetches photos using their `id`. Can you add that too?

**Comment by Samridhi-98** [comment]
> @Samridhi-98 #92 Adds an endpoint that fetches photos using their `id`. Can you add that too?

Sure, will do that.

**Comment by Samridhi-98** [comment]
@ShauryaAg  Done!

**Review by ShauryaAg — APPROVED** [review]

**Pull request merged**
