### PR TITLE
documentation on running eslint scripts

### PR DESCRIPTION
**Pull request by subhangi2731**
closes issue #152

### CODE REVIEW

**Comment by subhangi2731** [comment]
@adityabisoi please review and merge my pr

**Comment by adityabisoi** [comment]
We already have the rules and configuration files setup. You only need to add the installation instructions.

**Comment by subhangi2731** [comment]
@adityabisoi ok I will do the changes

**Comment by subhangi2731** [comment]
@adityabisoi done the changes please merge my pr

**Comment by adityabisoi** [comment]
lgtm

**Pull request merged**
