### PR TITLE
Added POST route to users route

### LINKED ISSUE #37: Add POST method
Add `POST` method to `/users` endpoint.

The method **should not** allow the request to manipulate any data on the database. Instead, the data sent by the user should be returned exactly as it is, with an additional field `timestamp` with the current timestamp, and a positive response code `200`

### PR DESCRIPTION
**Pull request by ritik307**
# Related Issue

-   closes #37 

# Proposed Changes

- [x] Add `POST` method to `/users` endpoint.
- [x] The method should not allow the request to manipulate any data on the database.
- [x] the data sent by the user should be returned exactly as it is, with an additional field `timestamp` with the current timestamp, and a positive response code `200`

# Checklist

-   [x] Tests
-   [x] Translations
-   [x] Documentation

### CODE REVIEW

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg Plz review

**Comment by paramsiddharth** [comment]
I have reviewed the code and it looks good to me! Give me some time, I'll discuss this update and tell you if we need any changes.

**Review by ShauryaAg — CHANGES_REQUESTED** [review]
Instead of sending back the `req.body` as it is, please validate the data first and don't send the unnecessary fields in the response.

**Comment by ritik307** [comment]
> 
> 
> Instead of sending back the `req.body` as it is, please validate the data first and don't send the unnecessary fields in the response.

sure will do that

**Comment by ritik307** [comment]
@ShauryaAg Done! Plz review

**Review by ShauryaAg — APPROVED** [review]

**Comment by ritik307** [comment]
@ShauryaAg @paramsiddharth Kindly add  `GSSOC'21` and `level` tags

**Pull request merged**
