### PR TITLE
added users delete endpoint

### PR DESCRIPTION
**Pull request by EANimesha**
for issue #50

### CODE REVIEW

**Comment by paramsiddharth** [comment]
Similar to the `/usertest` endpoint, for the faked deletion, the user ID must be checked for and the appropriate user must be returned as the `data` attribute of the response.
```js
{
    "data": userObject // The object pertaining to the user
}
```
Also, for an non-existent user ID, an error must be returned.

**Comment by EANimesha** [comment]
@paramsiddharth  Issue # 50 mentioned that the response should be 204 and empty content. So how to send the data attribute with the response?

**Comment by paramsiddharth** [comment]
> @paramsiddharth Issue # 50 mentioned that the response status should be 204 and empty content. So how to send the data attribute with the response?

I understand. Keep it 204 with an empty response and add an error message for a non-existent user ID.

**Review by paramsiddharth — APPROVED** [review]
Looks good to me!

**Pull request merged**
