### PR TITLE
Made model folder for user schema and fixed imports

### PR DESCRIPTION
**Pull request by Samridhi-98**
**Description:**
Made separate directory `models`  for user schema and updated all import statements for the user schema.

**Issue fix:** #45 

**Change/Requirements:**
- [x] Move user.ts in a separate models/ directory.
- [x] Fix all the user imports

### CODE REVIEW

**Comment by Samridhi-98** [comment]
@ShauryaAg Please review my PR, I have made all the changes as you mentioned in the issue.

**Review by ShauryaAg — CHANGES_REQUESTED** [review]
Why did you delete `.env.example`

**Comment by Samridhi-98** [comment]
> Why did you delete `.env.example`

I have replaced it with my .env, i will add it again.

**Comment by Samridhi-98** [comment]
@ShauryaAg  Added .env.example

**Review by ShauryaAg — APPROVED** [review]

**Pull request merged**
