### PR TITLE
created homepage and added content about existing routes

### LINKED ISSUE #142: Create homepage
Create a homepage and add information about existing routes

### PR DESCRIPTION
**Pull request by subhangi2731**
# Related Issue
created homepage and added content about existing routes

-   closes #142

# Checklist

-   [x] Tests
-   [x] Translations
-   [x] Documentation

### CODE REVIEW

**Comment by subhangi2731** [comment]
@adityabisoi @paramsiddharth  please review and merge my pr

**Comment by subhangi2731** [comment]
Screenshot from 2021-05-25 16-39-57
Screenshot from 2021-05-25 16-40-09
Screenshot from 2021-05-25 16-40-14

**Comment by paramsiddharth** [comment]
@adityabisoi Do we need to give information about the `usertest` endpoint in the front-end?

**Comment by adityabisoi** [comment]
@subhangi2731 Nice to see the project finally getting a frontend. @paramsiddharth I do not think that is necessary, since that is used only for testing and should not be provided to the user.

**Comment by paramsiddharth** [comment]
> @subhangi2731 Nice to see the project finally getting a frontend. @paramsiddharth I do not think that is necessary, since that is used only for testing and should not be provided to the user.

@subhangi2731 Please remove any information about the `usertest` endpoint from all webpages. The rest looks great!

**Comment by subhangi2731** [comment]
@adityabisoi @paramsiddharth thank u okay I remove the content of usertest endpoint

**Comment by subhangi2731** [comment]
Screenshot from 2021-05-26 09-44-18

**Comment by subhangi2731** [comment]
@adityabisoi @paramsiddharth I have done the changes please merge my pr

**Comment by subhangi2731** [comment]
@adityabisoi merge my pr please

**Comment by subhangi2731** [comment]
@adityabisoi please assign label and level tags to this pr I have not been assigned scores

**Pull request merged**
