### PR TITLE
Added books route

### LINKED ISSUE #110: Adding Books route.
**Describe the feature**
Add anime route with JSON having `title` `author` `rating` `description` `price`.

**Tasks Todo**
- [ ] Add  json file with appropiate data in `booksdata.json`.
- [ ] Add endpoint `/books` in `books.ts`.
- [ ] Add enpoint `/books/:id` in `books.ts`.

**Are you working on this feature? (Yes)**

### PR DESCRIPTION
**Pull request by ritik307**
# Related Issue

-   closes #110 

# Proposed Changes

- [x] Add  json file with appropiate data in `booksdata.json`.
- [x] Add endpoint `/books` in `books.ts`.
- [x] Add enpoint `/books/:id` in `books.ts`.

# Checklist

-   [x] Tests
-   [x] Translations
-   [x] Run eslint
image

### CODE REVIEW

**Comment by ritik307** [comment]
@paramsiddharth @ShauryaAg Plz review

**Comment by paramsiddharth** [comment]
@ritik307 Please resolve the conflicts and push a commit. I'll merge the PR then.

**Comment by ritik307** [comment]
@paramsiddharth Done!

**Comment by paramsiddharth** [comment]
Thank you!

**Pull request merged**
